function Reports(){}Reports.prototype=new GenericSfdcPage;Reports.percList={pie:1,donut:1,funnel:1};Reports.xAxisList={bar_0:1,bar_1:1,bar_2:1};Reports.yAxisList={column_0:1,column_1:1,column_2:1};Reports.noLegendList={bar_0:1,column_0:1,line_0:1,line_4:1};Reports.noShowValueList={bar_2:1,bar_3:1,column_2:1,column_3:1,line_1:1,line_5:1};Reports.onChartList={pie:1,donut:1,funnel:1};Reports.multiMetricList={column_1:1,column_2:1,line_0:1,line_4:1};
Reports.valueSelectIdList=[ChartConstants.pCHART_SUMMARY_2,ChartConstants.pCHART_SUMMARY_3,ChartConstants.pCHART_SUMMARY_4];Reports.summaryIsNumberList={"Record Count":1,N:1,B:1};Reports.prototype.registerTopNEvents=function(){var a=document.getElementById("topn");addEvent(a,"change",this.showTopNSections,false)};
Reports.prototype.showTopNSections=function(){var a=document.getElementById("topn"),b=document.getElementById("sortbyrow"),c=document.getElementById("orderrow"),d=document.getElementById("topn_custom"),e=document.getElementById("top_custom_section");if(a.value=="all"){b.style.display="none";c.style.display="none";e.style.display="none";b.style.display="none"}else if(a.value=="custom"){b.style.display="";c.style.display="";e.style.display="inline";d.focus()}else{b.style.display="";c.style.display=
"";e.style.display="none"}};
Reports.prototype.initFch=function(){this.headerMarker=document.getElementById(ReportsFch.FCH_AREA);this.headerMarkerY=getObjY(this.headerMarker)+20;this.floatingHeader=document.getElementById(ReportsFch.FLOATING_HEADER);this.headerX=getObjX(this.headerMarker)-parseInt(XBrowser.getCurrentStyle(this.floatingHeader,"paddingLeft"),10);this.isVisible=false;this.floatingHeader.style.display="none";if(XBrowser.userAgent.isIE6)this.floatingHeader.style.position="absolute";this.matchHeaderSize();var a=this;
addEvent(window,"scroll",function(){a.handleFchScroll()},false);addEvent(window,"resize",function(){a.matchHeaderSize()},false)};
Reports.prototype.matchHeaderSize=function(){var a=this.floatingHeader.childNodes[0].rows[0].cells,b=document.getElementById(ReportsFch.HEADER_ROW+"_0");if(b){this.floatingHeader.style.width=b.offsetWidth+"px";for(var c=["paddingLeft","paddingRight","borderLeftWidth","borderRightWidth"],d=0;d<b.cells.length;d++){for(var e=b.cells[d],f=0,g=0;g<c.length;g++){var j=parseInt(XBrowser.getCurrentStyle(e,c[g]),10);isNaN(j)||(f+=j)}a[d].style.width=e.offsetWidth-f+"px"}this.floatingHeader.style.left=(XBrowser.userAgent.isIE6?
this.headerX:this.headerX-getScrollX())+"px";this.headerBottomY=this.headerMarkerY+this.headerMarker.offsetHeight-70-this.floatingHeader.offsetHeight}};
Reports.prototype.handleFchScroll=function(){var a=getScrollY();a=a>=this.headerMarkerY&&a<this.headerBottomY;if(this.isVisible)if(a){if(XBrowser.userAgent.isIE6)this.floatingHeader.style.top=getScrollY()-85+"px";if(!XBrowser.userAgent.isIE6)this.floatingHeader.style.left=this.headerX-getScrollX()+"px"}else{this.floatingHeader.style.display="none";this.isVisible=false}else if(a){this.matchHeaderSize();this.floatingHeader.style.display="block";this.headerBottomY=this.headerMarkerY+this.headerMarker.offsetHeight-
70-this.floatingHeader.offsetHeight;this.isVisible=true}};Reports.oldSummaryValue=null;Reports.saveOldSummaryValueIfExists=function(){if(document.getElementById(ReportConstants.pSubTotalBy0)!==null)Reports.oldSummaryValue=document.getElementById(ReportConstants.pSubTotalBy0).value};
Reports.runReportPageOnSubmit=function(a,b,c){var d=document.getElementById(ReportConstants.pSubTotalBy0);if(d!==null&&Reports.oldSummaryValue!=d.value)if(document.forms[a][b].value=="t"&&document.getElementById(ReportConstants.pSubTotalBy0).value===""){document.forms[a][b].value="tt";for(b=0;b<c;b++)document.forms[a]["break"+b].value=""}else if(document.forms[a][b].value=="tt"&&document.getElementById(ReportConstants.pSubTotalBy0).value!=="")document.forms[a][b].value="t"};
Reports.formatPageOnSubmit=function(a,b){if(document.getElementById("format_tabular").checked===true)for(var c=0;c<b;c++){var d=document.forms[a]["break"+c];if(d)d.value=""}};
Reports.getChartStepIds=function(){var a={ct:"ct",showPercCell:"showPercCell",showTotalCell:"showTotalCell",showValues:"showValues",showPercentages:"showPercentages",showLabels:"showLabels",showValueCell:"showValueCell",dlsr:"dlsr",othersRow:"othersRow",smr:"smr"};if(UserContext.isAccessibleMode){a.showValues="chsv_pcl";a.showPercentages="chsp_pcl";a.showLabels="sal_pcl"}return a};
Reports.handleExtraDisplayOptions=function(a,b){var c=Reports.getChartStepIds(),d=document.getElementById(c.ct).options[a].value;if(Reports.percList[d]==1)document.getElementById(c.showPercCell).style.visibility="visible";else{document.getElementById(c.showPercCell).style.visibility="hidden";document.getElementById(ChartConstants.pCHART_SHOW_PERCENTAGE).checked=false}if(d=="donut")document.getElementById(c.showTotalCell).style.visibility="visible";else{document.getElementById(c.showTotalCell).style.visibility=
"hidden";document.getElementById(ChartConstants.pCHART_SHOW_TOTAL).checked=false}if(Reports.xAxisList[d]==1)document.getElementById(c.showValues).innerHTML=LC.getLabel("Report","showxAxisValues");else if(Reports.yAxisList[d]==1)document.getElementById(c.showValues).innerHTML=LC.getLabel("Report","showyAxisValues");else document.getElementById(c.showValues).innerHTML=LC.getLabel("Report","showValues");if(d=="pie"||d=="donut")document.getElementById(c.showPercentages).innerHTML=LC.getLabel("Report",
"showWedgePercentage");else if(d=="funnel")document.getElementById(c.showPercentages).innerHTML=LC.getLabel("Report","showSegmentPercentage");else document.getElementById(c.showPercentages).innerHTML=LC.getLabel("Report","showGroupPercentage");if(d=="pie"&&b)document.getElementById(ChartConstants.pCHART_SHOW_VALUES).checked=true;if(Reports.onChartList[d]==1)document.getElementById(c.showLabels).innerHTML=LC.getLabel("Report","showLabels");else document.getElementById(c.showLabels).innerHTML=LC.getLabel("Report",
"showaxislabels");if(Reports.noShowValueList[d]==1){document.getElementById(c.showValueCell).style.visibility="hidden";document.getElementById(ChartConstants.pCHART_SHOW_VALUES).checked=false}else document.getElementById(c.showValueCell).style.visibility="visible";var e=document.getElementById("l");if(Reports.onChartList[d]==1){if(e.options[e.length-1].value!="3")e.options[e.length]=new Option(LC.getLabel("ChartLegendPosition","3"),"3")}else e.options[e.length-1].value=="3"&&e.remove(e.length-1);
e=document.getElementById(c.dlsr);if(e!==null)e.style.display=Reports.onChartList[d]==1?"":"none";e=document.getElementById(c.othersRow);if(e!==null)if(Reports.percList[d]==1){e.style.display="block";if(b)if(d!="funnel")document.getElementById(ChartConstants.pCOMBINE_OTHERS).checked=true;else document.getElementById(ChartConstants.pCOMBINE_OTHERS).checked=false}else e.style.display="none";if(document.getElementById(ChartConstants.pCHART_USE_MULTI)!==null){c=document.getElementById(c.smr);if(Reports.multiMetricList[d]==
1||d=="bar_0"||d=="column_0")c.style.display="block";else{c.style.display="none";Reports.handleMultiMetricLegendOption(a)}Reports.handleMultiMetricOptions()}else Reports.handleMultiMetricLegendOption(a)};
Reports.handleMultiMetricOptions=function(){var a=document.getElementById(ChartConstants.pCHART_USE_MULTI),b=document.getElementById("ct").options[document.getElementById("ct").selectedIndex].value;Reports.handleMultiMetricDisplayAs();if(a.checked===true){if(Reports.multiMetricList[b]==1){document.getElementById("csm2").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=false;document.getElementById("shar").style.display="block";if(b!="line_0"&&b!="line_4")document.getElementById("uda").style.display=
"";else{document.getElementById("uda").style.display="none";document.getElementById(ChartConstants.pCHART_DIFF_AXIS).checked=false;Reports.filterInvalidSummaryChoices()}document.getElementById("csm3").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=true;document.getElementById("csm4").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=true;document.getElementById("rmcs2").style.display="none";document.getElementById("ansr").style.display=
"none";document.getElementById(ChartConstants.pCHART_SHOW_AS).value=ChartConstants.ONLY_LINE;if(document.getElementById(ChartConstants.pCHART_SUMMARY_2).value==="")document.getElementById(ChartConstants.pCHART_SUMMARY_2).selectedIndex="0"}else if(b=="column_0"){document.getElementById("shar").style.display="block";document.getElementById("uda").style.display="";document.getElementById(ChartConstants.pCHART_SHOW_AS).options[0].innerHTML=LC.getLabel("Report","moreColumns");Reports.toggleExtraChartSummaryOptions()}else if(b==
"bar_0"){document.getElementById("shar").style.display="block";document.getElementById("uda").style.display="none";document.getElementById(ChartConstants.pCHART_SHOW_AS).value=ChartConstants.MORE_BARS;document.getElementById(ChartConstants.pCHART_SHOW_AS).options[0].innerHTML=LC.getLabel("Report","moreBars");Reports.toggleExtraChartSummaryOptions()}else{document.getElementById("shar").style.display="none";document.getElementById("csm2").style.display="none";document.getElementById("csm3").style.display=
"none";document.getElementById("csm4").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=true;document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=true;document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=true;document.getElementById("ansr").style.display="none"}a=document.getElementById("l");a.disabled=false;a.options[0].value===""&&a.remove(0)}else{document.getElementById("csm2").style.display="none";document.getElementById("csm3").style.display=
"none";document.getElementById("csm4").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=true;document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=true;document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=true;document.getElementById("uda").style.display="none";document.getElementById("shar").style.display="none";document.getElementById("ansr").style.display="none";Reports.handleMultiMetricLegendOption(document.getElementById("ct").selectedIndex)}Reports.displayMultiMetricImage()};
Reports.handleMultiMetricLegendOption=function(a){var b=document.getElementById("ct").options[a].value;a=document.getElementById("l");if(Reports.noLegendList[b]==1){if(a.options[0].value!==""){b=document.createElement("option");b.innerHTML=LC.getLabel("SelectElement","Required");b.value="";a.insertBefore(b,a.firstChild)}a.selectedIndex=0;a.disabled=true}else{a.disabled=false;a.options[0].value===""&&a.remove(0)}};
Reports.handleMultiMetricDisplayAs=function(){var a=document.getElementById("ct").options[document.getElementById("ct").selectedIndex].value,b=document.getElementById(ChartConstants.pCHART_SHOW_AS).options[document.getElementById(ChartConstants.pCHART_SHOW_AS).selectedIndex].value;document.getElementById(ChartConstants.pCHART_SHOW_AS).length=0;var c=document.getElementById(ChartConstants.pCHART_SHOW_AS),d=document.createElement("option");if(Reports.multiMetricList[a]==1){d.value=ChartConstants.ONLY_LINE;
d.text=a=="line_4"?LC.getLabel("Report","cumulativeLine"):LC.getLabel("Report","onlyLine");c.options.add(d)}else if(a=="bar_0"){d.value=ChartConstants.MORE_BARS;d.text=LC.getLabel("Report","moreBars");c.options.add(d)}else{d.value=ChartConstants.MORE_BARS;d.text=LC.getLabel("Report","moreColumns");c.options.add(d);a=document.createElement("option");a.value=ChartConstants.ONLY_LINE;a.text=LC.getLabel("Report","onlyLine");c.options.add(a);if(b==ChartConstants.ONLY_LINE)c.selectedIndex=1}};
Reports.toggleExtraChartSummaryOptions=function(){var a=document.getElementById(ChartConstants.pCHART_SHOW_AS).options[document.getElementById(ChartConstants.pCHART_SHOW_AS).selectedIndex].value;Reports.reshuffleSummaryValues();document.getElementById("csm2").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=false;if(document.getElementById(ChartConstants.pCHART_SUMMARY_2).value==="")document.getElementById(ChartConstants.pCHART_SUMMARY_2).selectedIndex="0";if(a==
ChartConstants.MORE_BARS){a=document.getElementById(ChartConstants.pCHART_SUMMARY_2).value;var b=document.getElementById(ChartConstants.pCHART_SUMMARY_3).value,c=document.getElementById(ChartConstants.pCHART_SUMMARY_4).value;if(a!==""){document.getElementById("csm2").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=false}if(b!==""){document.getElementById("csm3").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=false}else{document.getElementById("csm3").style.display=
"none";document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=true}if(c!==""){document.getElementById("csm4").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=false}else{document.getElementById("csm4").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=true}Reports.handleAddNewSummaryLink();Reports.handleRemoveSummaryLink();document.getElementById("uda").style.display="none";document.getElementById("chda").checked=
false}else{document.getElementById("csm3").style.display="none";document.getElementById("csm4").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=true;document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=true;document.getElementById("ansr").style.display="none";document.getElementById("rmcs2").style.display="none";document.getElementById("rmcs3").style.display="none";document.getElementById("rmcs4").style.display="none";document.getElementById("uda").style.display=
""}Reports.filterInvalidSummaryChoices()};
Reports.showNextSummaryPicklist=function(){var a=document.getElementById(ChartConstants.pCHART_SUMMARY_2),b=document.getElementById(ChartConstants.pCHART_SUMMARY_3),c=document.getElementById(ChartConstants.pCHART_SUMMARY_4);Reports.reshuffleSummaryValues();Reports.reShowSummaryTableRows();if(a.value===""){document.getElementById("csm2").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=false;a.value=a.options[0].value;a.focus()}else if(b.value===""){document.getElementById("csm3").style.display=
"block";document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=false;b.value=b.options[0].value;b.focus()}else{document.getElementById("csm4").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=false;c.value=c.options[0].value;c.focus()}Reports.handleAddNewSummaryLink();Reports.handleRemoveSummaryLink()};
Reports.handleAddNewSummaryLink=function(){var a=document.getElementById("csm2").style.display,b=document.getElementById("csm3").style.display,c=document.getElementById("csm4").style.display;if(a=="block"&&b=="block"&&c=="block")document.getElementById("ansr").style.display="none";else document.getElementById("ansr").style.display="block"};
Reports.handleRemoveSummaryLink=function(){var a=document.getElementById("csm2").style.display,b=document.getElementById("csm3").style.display,c=document.getElementById("csm4").style.display;if(a=="block"&&b=="none"&&c=="none")document.getElementById("rmcs2").style.display="none";else document.getElementById("rmcs2").style.display="";if(a=="none"&&b=="block"&&c=="none")document.getElementById("rmcs3").style.display="none";else document.getElementById("rmcs3").style.display="";if(a=="none"&&b=="none"&&
c=="block")document.getElementById("rmcs4").style.display="none";else document.getElementById("rmcs4").style.display=""};Reports.hideSummaryPicklist=function(a,b){document.getElementById(b).style.display="none";document.getElementById(a).selectedIndex="-1";document.getElementById(a).disabled=true;Reports.handleAddNewSummaryLink();Reports.handleRemoveSummaryLink();document.getElementById("ansl").focus()};
Reports.reshuffleSummaryValues=function(){for(var a=[],b=0,c=0;c<Reports.valueSelectIdList.length;c++){var d=document.getElementById(Reports.valueSelectIdList[c]).value;if(d!==""){a[b]=d;b++}}for(b=0;b<Reports.valueSelectIdList.length;b++)if(a[b]!==undefined)document.getElementById(Reports.valueSelectIdList[b]).value=a[b];else document.getElementById(Reports.valueSelectIdList[b]).selectedIndex="-1"};
Reports.reShowSummaryTableRows=function(){var a=document.getElementById(ChartConstants.pCHART_SUMMARY_2).value,b=document.getElementById(ChartConstants.pCHART_SUMMARY_3).value,c=document.getElementById(ChartConstants.pCHART_SUMMARY_4).value;if(a!==""){document.getElementById("csm2").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=false}else{document.getElementById("csm2").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_2).disabled=
true}if(b!==""){document.getElementById("csm3").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=false}else{document.getElementById("csm3").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_3).disabled=true}if(c!==""){document.getElementById("csm4").style.display="block";document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=false}else{document.getElementById("csm4").style.display="none";document.getElementById(ChartConstants.pCHART_SUMMARY_4).disabled=
true}};
Reports.filterInvalidSummaryChoices=function(){var a=document.getElementById(ChartConstants.pCHART_SUMMARY).options[document.getElementById(ChartConstants.pCHART_SUMMARY).selectedIndex].value;a=summaryDataTypeMap[a];var b=document.getElementById(ChartConstants.pCHART_DIFF_AXIS),c=document.getElementById(ChartConstants.pCHART_SUMMARY_2).value,d=document.getElementById(ChartConstants.pCHART_SUMMARY_3).value,e=document.getElementById(ChartConstants.pCHART_SUMMARY_4).value;if(b.checked){document.getElementById(ChartConstants.pCHART_SUMMARY_2).length=0;
document.getElementById(ChartConstants.pCHART_SUMMARY_3).length=0;document.getElementById(ChartConstants.pCHART_SUMMARY_4).length=0;Reports.addAllSummaryOptions(ChartConstants.pCHART_SUMMARY_2,c);Reports.addAllSummaryOptions(ChartConstants.pCHART_SUMMARY_3,d);Reports.addAllSummaryOptions(ChartConstants.pCHART_SUMMARY_4,e)}else{document.getElementById(ChartConstants.pCHART_SUMMARY_2).length=0;document.getElementById(ChartConstants.pCHART_SUMMARY_3).length=0;document.getElementById(ChartConstants.pCHART_SUMMARY_4).length=
0;Reports.addCorrectSummaryOptions(ChartConstants.pCHART_SUMMARY_2,a,c);Reports.addCorrectSummaryOptions(ChartConstants.pCHART_SUMMARY_3,a,d);Reports.addCorrectSummaryOptions(ChartConstants.pCHART_SUMMARY_4,a,e)}};
Reports.addCorrectSummaryOptions=function(a,b,c){var d=document.getElementById(ChartConstants.pCHART_SUMMARY);a=document.getElementById(a);for(var e=0;e<d.length;e++){var f=d.options[e].value;if(summaryDataTypeMap[f]==b||Reports.summaryIsNumberList[summaryDataTypeMap[f]]==1&&Reports.summaryIsNumberList[b]==1){var g=document.createElement("option");g.value=f;g.text=d.options[e].text;a.options.add(g)}}if(summaryDataTypeMap[c]==b)a.value=c;else if(Reports.summaryIsNumberList[summaryDataTypeMap[c]]==
1&&Reports.summaryIsNumberList[b]==1)a.value=c;if(c==="")a.selectedIndex="-1"};Reports.addAllSummaryOptions=function(a,b){for(var c=document.getElementById(ChartConstants.pCHART_SUMMARY),d=document.getElementById(a),e=0;e<c.length;e++){var f=document.createElement("option");f.value=c.options[e].value;f.text=c.options[e].text;d.options.add(f)}d.value=b;if(b==="")d.selectedIndex="-1"};
Reports.displayMultiMetricImage=function(){var a=document.getElementById("ct").options[document.getElementById("ct").selectedIndex].value,b=document.getElementById(ChartConstants.pCHART_SHOW_AS).options[document.getElementById(ChartConstants.pCHART_SHOW_AS).selectedIndex].value,c=document.getElementById(ChartConstants.pCHART_DIFF_AXIS).checked;if(document.getElementById(ChartConstants.pCHART_USE_MULTI).checked&&(Reports.multiMetricList[a]==1||a=="bar_0"||a=="column_0"))if(a=="bar_0")if(b==ChartConstants.MORE_BARS){a=
document.getElementById("csm2").style.display;b=document.getElementById("csm3").style.display;c=document.getElementById("csm4").style.display;var d=0;if(a=="block")d+=1;if(b=="block")d+=1;if(c=="block")d+=1;if(d==1)document.getElementById("ci").src=chartImagePathMap.bargrpAddOne;else if(d==2)document.getElementById("ci").src=chartImagePathMap.bargrpAddTwo;else if(d==3)document.getElementById("ci").src=chartImagePathMap.bargrpAddThree}else{if(b==ChartConstants.ONLY_LINE)if(c)document.getElementById("ci").src=
chartImagePathMap.barSecAxis;else document.getElementById("ci").src=chartImagePathMap.barLine}else if(a=="bar_1")if(b==ChartConstants.MORE_BARS)document.getElementById("ci").src=chartImagePathMap.bargrpWBar;else{if(b==ChartConstants.ONLY_LINE)if(c)document.getElementById("ci").src=chartImagePathMap.bargrpSecAxis;else document.getElementById("ci").src=chartImagePathMap.bargrpLine}else if(a=="bar_2")if(c)document.getElementById("ci").src=chartImagePathMap.barstkSecAxis;else document.getElementById("ci").src=
chartImagePathMap.barstkLine;else if(a=="column_0")if(b==ChartConstants.MORE_BARS){a=document.getElementById("csm2").style.display;b=document.getElementById("csm3").style.display;c=document.getElementById("csm4").style.display;d=0;if(a=="block")d+=1;if(b=="block")d+=1;if(c=="block")d+=1;if(d==1)document.getElementById("ci").src=chartImagePathMap.colgrpAddOne;else if(d==2)document.getElementById("ci").src=chartImagePathMap.colgrpAddTwo;else if(d==3)document.getElementById("ci").src=chartImagePathMap.colgrpAddThree}else{if(b==
ChartConstants.ONLY_LINE)if(c)document.getElementById("ci").src=chartImagePathMap.colSecAxis;else document.getElementById("ci").src=chartImagePathMap.colLine}else if(a=="column_1")if(b==ChartConstants.MORE_BARS)document.getElementById("ci").src=chartImagePathMap.colgrpWBar;else{if(b==ChartConstants.ONLY_LINE)if(c)document.getElementById("ci").src=chartImagePathMap.colgrpSecAxis;else document.getElementById("ci").src=chartImagePathMap.colgrpLine}else if(a=="column_2")if(c)document.getElementById("ci").src=
chartImagePathMap.colstkSecAxis;else document.getElementById("ci").src=chartImagePathMap.colstkLine;else if(a=="line_0")document.getElementById("ci").src=chartImagePathMap.lineline;else{if(a=="line_4")document.getElementById("ci").src=chartImagePathMap.linecumlinecum}else document.getElementById("ci").src=chartImages[document.getElementById("ct").selectedIndex]};
function HoverTooltipHandler(a,b,c){this.controller=a;this.div=b;b.style.display="block";this.origHeight=b.firstChild.offsetHeight;this.shim=new iframeShim(b);this.saveOrigPos=c;var d=this;this.setPosition=function(e){if(!e)e=d.shim;var f=d.controller,g=getOffsetLeft(f),j=getObjY(f),h=f.offsetWidth;f=f.offsetHeight;var k=g+d.div.offsetWidth,i=getScrollX()+getWindowWidth()-15;e.div.style.left=(k<=i?g+h+5:g-d.div.offsetWidth-5)+"px";g=getScrollY();h=j-15-d.div.offsetHeight;if(h<g)h=j+f+15;e.div.style.top=
h+"px";d.div.style.height=d.origHeight+"px"};this.mover=new Fader(this.shim,function(e){return e.getOpacity()<=0},function(e){return e.getOpacity()>=0.99},30,function(e,f){return e+f*0.2},function(e,f){e.setOpacity(f)},0,function(e){e.setOpacity(0);e.setStyle("display","none")},function(e){e.setOpacity(0.99);e.setStyle("display","block")},this.setPosition);this.fadeIn=function(){d.mover.fadeIn()};this.fadeOut=function(){d.mover.fadeOut()}}
function HoverTooltip(a,b){this.mover=new HoverTooltipHandler(a,b,true);var c=this;this.handleMouseOver=function(){c.mover.fadeIn()};this.handleMouseOut=function(){c.mover.fadeOut();for(var d=0;d<HoverTooltip.TOOLTIP_FADE_MAP.length;d++)if(HoverTooltip.TOOLTIP_FADE_MAP[d]===a){HoverTooltip.TOOLTIP_FADE_MAP.splice(d,1);break}};this.init()}HoverTooltip.prototype={};
HoverTooltip.prototype.init=function(){addEvent(this.mover.controller,"mouseover",this.handleMouseOver,false);addEvent(this.mover.controller,"mouseout",this.handleMouseOut,false);addEvent(this.mover.div,"mouseover",this.handleMouseOver,false);addEvent(this.mover.div,"mouseout",this.handleMouseOut,false)};HoverTooltip.TOOLTIP_FADE_MAP=[];HoverTooltip.TOOLTIP_TEXTCONTAINER_MAP=[];
HoverTooltip.handleMouseOver=function(a){var b;for(b=0;b<HoverTooltip.TOOLTIP_FADE_MAP.length;b++)if(HoverTooltip.TOOLTIP_FADE_MAP[b]===a)return false;var c=a.id;if(c===null||c===undefined)return false;c=document.getElementById("tooltipTextDiv");if(!c){c=document.createElement("div");c.className=MouseOverElement.DEFAULT_CLASS_INNER;c.id="tooltipTextDiv";c.style.position="absolute";b=document.getElementsByTagName("body");if(b.length>0)b[0].appendChild(c);else return false}var d=HoverTooltip.getTooltipContainer(a.id);
if(!d){for(b=0;b<a.childNodes.length;b++)if(a.childNodes[b].className==HoverTooltipElement.DEFAULT_CLASS_TEXT){d=a.childNodes[b];break}if(!d)return;HoverTooltip.registerTooltipContainer(a.id,d)}c.innerHTML="<span>"+d.innerHTML+"</span>";(new HoverTooltip(a,c)).handleMouseOver();HoverTooltip.TOOLTIP_FADE_MAP[HoverTooltip.TOOLTIP_FADE_MAP.length]=a};HoverTooltip.registerTooltipContainer=function(a,b){HoverTooltip.TOOLTIP_TEXTCONTAINER_MAP[a]=b};
HoverTooltip.getTooltipContainer=function(a){a=HoverTooltip.TOOLTIP_TEXTCONTAINER_MAP[a];if(a!==null&&a!==undefined&&a.innerHTML.length>0)return a;return null};var filterLookupValueElem;
function openFilterLookupWindow(a,b,c,d){filterLookupValueElem=d;c=document.getElementById(c);c=c.options[c.selectedIndex];if(a!==null&&a!==undefined||b===null||b===undefined){a=document.getElementById(a);d=a.action;var e=a.target,f=a.lookup.value;if(b!==null&&b!==undefined)a.action=b;a.target="filter_lookup";a.lookup.value=c.value;a.submit();a.action=d;a.target=e;a.lookup.value=f}else curPopupWindow.location.href=b+"?lookup="+c.value+"&workflow=1"}function CSFEditor(){}
CSFEditor.slideInFunc=function(){document.getElementById("csfFuncRef").style.width="220px";document.getElementById("csfFuncWrapper").style.display="block";if(window.ActiveXObject){document.getElementById("csfFuncSelector").style.display="block";Animation.rollIn(document.getElementById("csfFuncRefFS"),function(){})}else Animation.rollIn(document.getElementById("csfFuncSelector"),function(){});document.getElementById("showRefLink").style.display="none"};
CSFEditor.slideOutFunc=function(){window.ActiveXObject?Animation.rollOut(document.getElementById("csfFuncRefFS"),function(){setTimeout(function(){document.getElementById("csfFuncWrapper").style.display="none";document.getElementById("csfFuncSelector").style.display="none"},20)}):Animation.rollOut(document.getElementById("csfFuncSelector"),function(){setTimeout(function(){document.getElementById("csfFuncWrapper").style.display="none"},20)});document.getElementById("csfFuncRef").style.width="0px";setTimeout(function(){document.getElementById("showRefLink").style.display=
"inline"},250)};
CSFEditor.showPossibleSummaryError=function(){var a;if(document.getElementById("functionSelector")!==null)a=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;var b=false,c=false;if(document.getElementById("csfContextallLevel")!==null)b=document.getElementById("csfContextallLevel").checked;if(document.getElementById("csfContextgrandTotalLevel")!==null)c=document.getElementById("csfContextgrandTotalLevel").checked;var d=false;if(document.getElementById("csfContextsub1Level")===
null)d=true;if(a=="PARENTGROUPVAL"&&(b||c)){if(d)document.getElementById("parNoGroupingErrorSpan").style.display="inline";else document.getElementById("parGroupValErrorSpan").style.display="inline";document.getElementById("prevNoGroupingErrorSpan").style.display="none";document.getElementById("prevGroupValErrorSpan").style.display="none";document.getElementById("sumPrevFuncHelperFS").style.display="none";document.getElementById("sumParentFuncHelperFS").style.display="none"}else if(a=="PREVGROUPVAL"&&
(b||c)){if(d)document.getElementById("prevNoGroupingErrorSpan").style.display="inline";else document.getElementById("prevGroupValErrorSpan").style.display="inline";document.getElementById("parNoGroupingErrorSpan").style.display="none";document.getElementById("parGroupValErrorSpan").style.display="none";document.getElementById("sumPrevFuncHelperFS").style.display="none";document.getElementById("sumParentFuncHelperFS").style.display="none"}else{if(document.getElementById("parGroupValErrorSpan")!==null)document.getElementById("parGroupValErrorSpan").style.display=
"none";if(document.getElementById("prevGroupValErrorSpan")!==null)document.getElementById("prevGroupValErrorSpan").style.display="none";if(document.getElementById("parNoGroupingErrorSpan")!==null)document.getElementById("parNoGroupingErrorSpan").style.display="none";if(document.getElementById("prevNoGroupingErrorSpan")!==null)document.getElementById("prevNoGroupingErrorSpan").style.display="none";if(document.getElementById("sumPrevFuncHelperFS")!==null)if(a=="PREVGROUPVAL"){document.getElementById("sumPrevFuncHelperFS").style.display=
"block";document.getElementById("sumParentFuncHelperFS").style.display="none"}else if(a=="PARENTGROUPVAL"){document.getElementById("sumParentFuncHelperFS").style.display="block";document.getElementById("sumPrevFuncHelperFS").style.display="none"}else{document.getElementById("sumPrevFuncHelperFS").style.display="none";document.getElementById("sumParentFuncHelperFS").style.display="none"}}};
CSFEditor.showImageAll=function(){if(document.getElementById("csfSumAll")!==null)document.getElementById("csfSumAll").style.display="inline";if(document.getElementById("csfSumSub1")!==null)document.getElementById("csfSumSub1").style.display="none";if(document.getElementById("csfSumSub2")!==null)document.getElementById("csfSumSub2").style.display="none";if(document.getElementById("csfSumSub3")!==null)document.getElementById("csfSumSub3").style.display="none";if(document.getElementById("csfSumGrand")!==
null)document.getElementById("csfSumGrand").style.display="none"};
CSFEditor.showImageSub1=function(){if(document.getElementById("csfSumAll")!==null)document.getElementById("csfSumAll").style.display="none";if(document.getElementById("csfSumSub1")!==null)document.getElementById("csfSumSub1").style.display="inline";if(document.getElementById("csfSumSub2")!==null)document.getElementById("csfSumSub2").style.display="none";if(document.getElementById("csfSumSub3")!==null)document.getElementById("csfSumSub3").style.display="none";if(document.getElementById("csfSumGrand")!==
null)document.getElementById("csfSumGrand").style.display="none"};
CSFEditor.showImageSub2=function(){if(document.getElementById("csfSumAll")!==null)document.getElementById("csfSumAll").style.display="none";if(document.getElementById("csfSumSub1")!==null)document.getElementById("csfSumSub1").style.display="none";if(document.getElementById("csfSumSub2")!==null)document.getElementById("csfSumSub2").style.display="inline";if(document.getElementById("csfSumSub3")!==null)document.getElementById("csfSumSub3").style.display="none";if(document.getElementById("csfSumGrand")!==
null)document.getElementById("csfSumGrand").style.display="none"};
CSFEditor.showImageSub3=function(){if(document.getElementById("csfSumAll")!==null)document.getElementById("csfSumAll").style.display="none";if(document.getElementById("csfSumSub1")!==null)document.getElementById("csfSumSub1").style.display="none";if(document.getElementById("csfSumSub2")!==null)document.getElementById("csfSumSub2").style.display="none";if(document.getElementById("csfSumSub3")!==null)document.getElementById("csfSumSub3").style.display="inline";if(document.getElementById("csfSumGrand")!==
null)document.getElementById("csfSumGrand").style.display="none"};
CSFEditor.showImageGrand=function(){if(document.getElementById("csfSumAll")!==null)document.getElementById("csfSumAll").style.display="none";if(document.getElementById("csfSumSub1")!==null)document.getElementById("csfSumSub1").style.display="none";if(document.getElementById("csfSumSub2")!==null)document.getElementById("csfSumSub2").style.display="none";if(document.getElementById("csfSumSub3")!==null)document.getElementById("csfSumSub3").style.display="none";if(document.getElementById("csfSumGrand")!==
null)document.getElementById("csfSumGrand").style.display="inline"};
CSFEditor.initSumImage=function(){var a=document.getElementById("csfContextallLevel").checked,b=false,c=false,d=false;document.getElementById("csfContextgrandTotalLevel");if(document.getElementById("csfContextsub1Level")!==null)b=document.getElementById("csfContextsub1Level").checked;if(document.getElementById("csfContextsub2Level")!==null)c=document.getElementById("csfContextsub2Level").checked;if(document.getElementById("csfContextsub3Level")!==null)d=document.getElementById("csfContextsub3Level").checked;
if(a)document.getElementById("csfSumAll").style.display="inline";else if(b)document.getElementById("csfSumSub1").style.display="inline";else if(c)document.getElementById("csfSumSub2").style.display="inline";else if(d)document.getElementById("csfSumSub3").style.display="inline";else document.getElementById("csfSumGrand").style.display="inline"};
CSFEditor.showProperColumns=function(){var a=false,b=false,c=false,d=false,e=false,f=false,g=false,j=false,h=false,k;if(document.getElementById("functionSelector")!==null)k=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;if(document.getElementById("funcFormat")!==null){if(k=="PREVGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PREVGROUPVAL");if(k=="PARENTGROUPVAL")document.getElementById("funcFormat").innerHTML=
LC.getLabel("FormulaFieldFunctions","PARENTGROUPVAL")}if(document.getElementById("csfContextsub1Level")!==null)a=document.getElementById("csfContextsub1Level").checked;if(document.getElementById("csfContextsub2Level")!==null)b=document.getElementById("csfContextsub2Level").checked;if(document.getElementById("csfContextsub3Level")!==null)c=document.getElementById("csfContextsub3Level").checked;if(document.getElementById("chosenGroupLevel1")!==null)d=true;if(document.getElementById("chosenGroupLevel2")!==
null)e=true;if(document.getElementById("chosenGroupLevel3")!==null)f=true;if(document.getElementById("chosenParentLevel0")!==null)g=true;if(document.getElementById("chosenParentLevel1")!==null)j=true;if(document.getElementById("chosenParentLevel2")!==null)h=true;if(k=="PREVGROUPVAL")if(a){if(d){document.getElementById("chosenGroupLevel1").disabled=false;document.getElementById("chosenGroupLevel1").checked=true;functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("ReportAggregatesStep","prevFuncInsertLabel",
document.getElementById("chosenGroupLevel1").value);if(e)document.getElementById("chosenGroupLevel2").disabled=true;if(f)document.getElementById("chosenGroupLevel3").disabled=true}}else if(b){if(d){document.getElementById("chosenGroupLevel1").disabled=false;if(e){document.getElementById("chosenGroupLevel2").disabled=false;document.getElementById("chosenGroupLevel2").checked=true;functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("ReportAggregatesStep","prevFuncInsertLabel",document.getElementById("chosenGroupLevel2").value)}if(f)document.getElementById("chosenGroupLevel3").disabled=
true}}else if(c){if(d){document.getElementById("chosenGroupLevel1").disabled=false;if(e)document.getElementById("chosenGroupLevel2").disabled=false;if(f){document.getElementById("chosenGroupLevel3").disabled=false;document.getElementById("chosenGroupLevel3").checked=true;functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("ReportAggregatesStep","prevFuncInsertLabel",document.getElementById("chosenGroupLevel3").value)}}}else functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("FormulaFieldFunctions",
"PREVGROUPVAL");else if(k=="PARENTGROUPVAL")if(a){if(g){document.getElementById("chosenParentLevel0").disabled=false;document.getElementById("chosenParentLevel0").checked=true;functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("ReportAggregatesStep","sumParentFuncInsertLabel",document.getElementById("chosenParentLevel0").value);if(j)document.getElementById("chosenParentLevel1").disabled=true;if(h)document.getElementById("chosenParentLevel2").disabled=true}}else if(b){if(j){document.getElementById("chosenParentLevel0").disabled=
false;if(e){document.getElementById("chosenParentLevel1").disabled=false;document.getElementById("chosenParentLevel1").checked=true;functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("ReportAggregatesStep","sumParentFuncInsertLabel",document.getElementById("chosenParentLevel1").value)}if(h)document.getElementById("chosenParentLevel2").disabled=true}}else if(c){if(h){document.getElementById("chosenParentLevel0").disabled=false;if(j)document.getElementById("chosenParentLevel1").disabled=false;if(h){document.getElementById("chosenParentLevel2").disabled=
false;document.getElementById("chosenParentLevel2").checked=true;functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("ReportAggregatesStep","sumParentFuncInsertLabel",document.getElementById("chosenParentLevel2").value)}}}else functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("FormulaFieldFunctions","PARENTGROUPVAL")};
CSFEditor.hideAggSelection=function(){var a=null;if(document.getElementById("calcagg_formula_v_field")!==null)a=document.getElementById("calcagg_formula_v_field").options[document.getElementById("calcagg_formula_v_field").selectedIndex].value;document.getElementById("summaryFieldValue").value=a;if(document.getElementById("calcagg_formula_v_type")!==null)if(a=="RowCount")document.getElementById("calcagg_formula_v_type").style.display="none";else document.getElementById("calcagg_formula_v_type").style.display=
"inline"};CSFEditor.setRowBreakContext=function(a){document.getElementById("calcagg_rowBreak_v").value=a};CSFEditor.setColBreakContext=function(a){document.getElementById("calcagg_colBreak_v").value=a};
CSFEditor.setGroupLevel=function(a){var b=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;if(document.getElementById("funcFormat")!==null){if(b=="PREVGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PREVGROUPVAL");if(b=="PARENTGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PARENTGROUPVAL")}functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("ReportAggregatesStep",
"prevFuncInsertLabel",a);functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("ReportAggregatesStep","sumParentFuncInsertLabel",a)};CSFEditor.showMatrixImageAll=function(){CSFEditor.hideMatrixImages();document.getElementById("csfMatrixAll").style.display="inline"};
CSFEditor.hideMatrixImages=function(){if(document.getElementById("csfMatrixAll")!==null)document.getElementById("csfMatrixAll").style.display="none";if(document.getElementById("csfMatrix1x1")!==null)document.getElementById("csfMatrix1x1").style.display="none";if(document.getElementById("csfMatrix1x2")!==null)document.getElementById("csfMatrix1x2").style.display="none";if(document.getElementById("csfMatrix1xGrand")!==null)document.getElementById("csfMatrix1xGrand").style.display="none";if(document.getElementById("csfMatrix2x1")!==
null)document.getElementById("csfMatrix2x1").style.display="none";if(document.getElementById("csfMatrix2x2")!==null)document.getElementById("csfMatrix2x2").style.display="none";if(document.getElementById("csfMatrix2xGrand")!==null)document.getElementById("csfMatrix2xGrand").style.display="none";if(document.getElementById("csfMatrixGrandx1")!==null)document.getElementById("csfMatrixGrandx1").style.display="none";if(document.getElementById("csfMatrixGrandx2")!==null)document.getElementById("csfMatrixGrandx2").style.display=
"none";if(document.getElementById("csfMatrixGrandxGrand")!==null)document.getElementById("csfMatrixGrandxGrand").style.display="none"};CSFEditor.showSubChoices=function(){document.getElementById("csfSubchoices").style.display="block"};CSFEditor.hideSubChoices=function(){document.getElementById("csfSubchoices").style.display="none"};
CSFEditor.autoSetContext=function(){var a=document.getElementById("rowLevel").options[document.getElementById("rowLevel").selectedIndex].value,b=document.getElementById("colLevel").options[document.getElementById("colLevel").selectedIndex].value;document.getElementById("calcagg_rowBreak_v").value=a;document.getElementById("calcagg_colBreak_v").value=b};
CSFEditor.showProperMatrixImage=function(){var a=document.getElementById("csfMatrixContextallLevel").checked,b=document.getElementById("rowLevel").selectedIndex,c=document.getElementById("colLevel").selectedIndex;if(a)document.getElementById("csfSubchoices").style.display="none";else document.getElementById("csfSubchoices").style.display="block";a?CSFEditor.showMatrixImageAll():CSFEditor.showMatrixImage(b,c)};
CSFEditor.showMatrixImage=function(a,b){CSFEditor.hideMatrixImages();var c=a+"",d=b+"";if(a===0)c="Grand";if(b===0)d="Grand";c="csfMatrix"+c+"x"+d;if(document.getElementById(c+"")!==null)document.getElementById(c+"").style.display="inline"};
CSFEditor.showPossibleMatrixError=function(){var a;if(document.getElementById("functionSelector")!==null)a=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;var b=0,c=0,d=false,e=false,f=false;if(document.getElementById("rowLevel")!==null)b=document.getElementById("rowLevel").selectedIndex;if(document.getElementById("colLevel")!==null)c=document.getElementById("colLevel").selectedIndex;if(document.getElementById("csfMatrixContextallLevel")!==
null)d=document.getElementById("csfMatrixContextallLevel").checked;if(document.getElementById("csfMatrixContextspecificLevel")!==null)e=document.getElementById("csfMatrixContextspecificLevel").checked;f=e&&b===0&&c===0;if(a=="PARENTGROUPVAL"&&d){document.getElementById("parGroupValErrorSpan").style.display="inline";document.getElementById("prevGroupValErrorSpan").style.display="none";document.getElementById("matrixParentFuncHelperFS").style.display="none";document.getElementById("matrixPrevFuncHelperFS").style.display=
"none"}else if(a=="PREVGROUPVAL"&&(d||f)){document.getElementById("prevGroupValErrorSpan").style.display="inline";document.getElementById("parGroupValErrorSpan").style.display="none";document.getElementById("matrixPrevFuncHelperFS").style.display="none";document.getElementById("matrixParentFuncHelperFS").style.display="none"}else{if(document.getElementById("parGroupValErrorSpan")!==null)document.getElementById("parGroupValErrorSpan").style.display="none";if(document.getElementById("prevGroupValErrorSpan")!==
null)document.getElementById("prevGroupValErrorSpan").style.display="none";if(document.getElementById("matrixPrevFuncHelperFS")!==null)if(a=="PREVGROUPVAL"){document.getElementById("matrixPrevFuncHelperFS").style.display="block";document.getElementById("matrixParentFuncHelperFS").style.display="none"}else if(a=="PARENTGROUPVAL"){document.getElementById("matrixParentFuncHelperFS").style.display="block";document.getElementById("matrixPrevFuncHelperFS").style.display="none"}else{document.getElementById("matrixPrevFuncHelperFS").style.display=
"none";document.getElementById("matrixParentFuncHelperFS").style.display="none"}}};
CSFEditor.showProperSelectColumns=function(){var a=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value,b=document.getElementById("rowLevel"),c=document.getElementById("colLevel"),d=false,e=0,f=0;if(document.getElementById("funcFormat")!==null){if(a=="PREVGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PREVGROUPVAL");if(a=="PARENTGROUPVAL")document.getElementById("funcFormat").innerHTML=
LC.getLabel("ReportAggregatesStep","matrixParentFuncFormatLabel")}if(document.getElementById("csfMatrixContextspecificLevel")!==null)d=document.getElementById("csfMatrixContextspecificLevel").checked;if(b!==null)e=b.selectedIndex;if(c!==null)f=c.selectedIndex;if(d)if(a=="PREVGROUPVAL")if(e===0&&f===0)functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("FormulaFieldFunctions","PREVGROUPVAL");else{var g=document.getElementById("matrixPrevFuncColumns"),j=document.createElement("optgroup");j.label=LC.getLabel("ReportAggregatesStep",
"matrixParentRowOptGroup")+"";var h=document.createElement("optgroup");h.label=LC.getLabel("ReportAggregatesStep","matrixParentColOptGroup")+"";var k;if(window.ActiveXObject){k=e;a=f}else{k=b.length;a=c.length}var i=1;for(i=1;i<=k;i++){if(i==b.length)break;d=document.createElement("option");var l=columnNameToFormulaNameMap[b.options[i].value];d.value=l;d.appendChild(document.createTextNode(b.options[i].text));if(i>e)d.disabled="disabled";j.appendChild(d)}for(b=b=1;b<=a;b++){if(b==c.length)break;d=
document.createElement("option");l=columnNameToFormulaNameMap[c.options[b].value];d.value=l;d.appendChild(document.createTextNode(c.options[b].text));if(b>f)d.disabled=true;h.appendChild(d)}for(;g.hasChildNodes();)g.removeChild(g.firstChild);j.hasChildNodes()&&g.appendChild(j);h.hasChildNodes()&&g.appendChild(h);c=document.getElementById("matrixPrevFuncColumns").options[document.getElementById("matrixPrevFuncColumns").options.selectedIndex].value;functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("ReportAggregatesStep",
"prevFuncInsertLabel",c)}else{if(a=="PARENTGROUPVAL"){g=document.getElementById("matrixParentRowColumns");g.options.length=0;document.getElementById("matrixParentRowColumns").options[g.options.length]=new Option(LC.getLabel("ReportAggregatesStep","matrixRowGrandSummaryLabel"),LC.getLabel("ReportAggregatesStep","matrixRowGrandSummaryValue"));if(window.ActiveXObject){k=e;a=f}else{k=b.length;a=c.length}for(i=1;i<=k;i++){if(i==b.length)break;d=document.createElement("option");l=columnNameToFormulaNameMap[b.options[i].value];
d.value=l;d.text=b.options[i].text;if(i>e)d.disabled=true;g.options.add(d)}e=document.getElementById("matrixParentColColumns");e.options.length=0;document.getElementById("matrixParentColColumns").options[e.options.length]=new Option(LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryLabel"),LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryValue"));for(b=1;b<=a;b++){if(b==c.length)break;d=document.createElement("option");l=columnNameToFormulaNameMap[c.options[b].value];d.value=l;d.text=
c.options[b].text;if(b>f)d.disabled=true;e.options.add(d)}c=document.getElementById("matrixParentRowColumns").options[document.getElementById("matrixParentRowColumns").options.selectedIndex].value;f=document.getElementById("matrixParentColColumns").options[document.getElementById("matrixParentColColumns").options.selectedIndex].value;functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("ReportAggregatesStep","matrixParentFuncInsertLabel",c,f)}}else{functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("FormulaFieldFunctions",
"PREVGROUPVAL");functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("ReportAggregatesStep","matrixParentFuncFormatLabel")}};
CSFEditor.setMatrixPrevFuncHelperColumn=function(a){var b=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;if(document.getElementById("funcFormat")!==null)if(b=="PREVGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PREVGROUPVAL");functionNameToPrototypeMap.PREVGROUPVAL=LC.getLabel("ReportAggregatesStep","prevFuncInsertLabel",a)};
CSFEditor.setMatrixParentRowHelperColumn=function(a){var b=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;if(document.getElementById("funcFormat")!==null)if(b=="PARENTGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("ReportAggregatesStep","matrixParentFuncFormatLabel");b=document.getElementById("matrixParentColColumns").options[document.getElementById("matrixParentColColumns").selectedIndex].value;functionNameToPrototypeMap.PARENTGROUPVAL=
LC.getLabel("ReportAggregatesStep","matrixParentFuncInsertLabel",a,b)};
CSFEditor.setMatrixParentColHelperColumn=function(a){var b=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;if(document.getElementById("funcFormat")!==null)if(b=="PARENTGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("ReportAggregatesStep","matrixParentFuncFormatLabel");b=document.getElementById("matrixParentRowColumns").options[document.getElementById("matrixParentRowColumns").selectedIndex].value;functionNameToPrototypeMap.PARENTGROUPVAL=
LC.getLabel("ReportAggregatesStep","matrixParentFuncInsertLabel",b,a)};CSFEditor.transferFuncSelectOpenParam=function(a,b){b.isFuncSelectorOpen.value=a.isFuncSelectorOpen.value};CSFEditor.resetHiddenTransferParams=function(){var a=document.report;if(!a)a=opener.document.report;a.isFuncSelectorOpen.value="false";a.funcSelectorValue.value="";a.funcCategoryValue.value="";a.summaryFieldValue.value="";a.aggTypeValue.value=""};
CSFEditor.transferFuncSelectorValueParam=function(a,b){b.funcSelectorValue.value=a.funcSelectorValue.value};CSFEditor.transferFuncCategoryValueParam=function(a,b){b.funcCategoryValue.value=a.funcCategoryValue.value};CSFEditor.transferSummaryFieldValueParam=function(a,b){b.summaryFieldValue.value=a.summaryFieldValue.value};CSFEditor.transferAggTypeValueParam=function(a,b){b.aggTypeValue.value=a.aggTypeValue.value};
CSFEditor.setFuncSelectorValueParam=function(){var a=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;document.getElementById("funcSelectorValue").value=a};CSFEditor.setFuncCategoryValueParam=function(){var a=document.getElementById("functionCategorySelector").options[document.getElementById("functionCategorySelector").selectedIndex].value;document.getElementById("funcCategoryValue").value=a};
CSFEditor.setFuncSelectorDefaultValue=function(a){document.getElementById("functionSelector").selectedIndex=0;document.getElementById("funcSelectorValue").value=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;FormulaEditor.setFunctionInfo(document.getElementById("funcSelectorValue").value);a=="matrix"?CSFEditor.showPossibleMatrixError():CSFEditor.showPossibleSummaryError()};
CSFEditor.initCategoryOptions=function(){for(var a=document.getElementById("funcCategoryValue").value,b=document.getElementById("functionCategorySelector"),c=-1,d=0;d<b.options.length;d++)if(b.options[d].value==a){c=d;break}if(c>=0)b.selectedIndex=c;FormulaEditor.setListToCategory(a,categoryNameToFunctionOptionsMap,"functionSelector","All",false);a=document.getElementById("funcSelectorValue").value;b=document.getElementById("functionSelector");c=-1;if(a==="")b.selectedIndex=0;else{for(d=0;d<b.options.length;d++)if(b.options[d].value==
a){c=d;break}if(c>=0)b.selectedIndex=c}};
CSFEditor.initSummaryFieldValue=function(){var a=document.getElementById("summaryFieldValue").value,b=document.getElementById("calcagg_formula_v_field"),c=-1;if(a==="")b.selectedIndex=0;else{for(var d=0;d<b.options.length;d++)if(b.options[d].value==a){c=d;break}if(c>=0)b.selectedIndex=c}if(a=="RowCount"||a==="")document.getElementById("calcagg_formula_v_type").style.display="none";else document.getElementById("calcagg_formula_v_type").style.display="inline";CSFEditor.initAggTypeValue()};
CSFEditor.resetFuncFormat=function(){var a;if(document.getElementById("functionSelector")!==null)a=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;if(document.getElementById("funcFormat")!==null){if(a=="PREVGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PREVGROUPVAL");if(a=="PARENTGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PARENTGROUPVAL")}};
CSFEditor.resetMatrixFuncFormat=function(){if(document.getElementById("functionSelector")!==null)selectedValue=document.getElementById("functionSelector").options[document.getElementById("functionSelector").selectedIndex].value;if(document.getElementById("funcFormat")!==null){if(selectedValue=="PREVGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("FormulaFieldFunctions","PREVGROUPVAL");if(selectedValue=="PARENTGROUPVAL")document.getElementById("funcFormat").innerHTML=LC.getLabel("ReportAggregatesStep",
"matrixParentFuncFormatLabel")}};CSFEditor.setAggTypeValueParam=function(){var a=document.getElementById("calcagg_formula_v_type").options[document.getElementById("calcagg_formula_v_type").selectedIndex].value;document.getElementById("aggTypeValue").value=a};
CSFEditor.initAggTypeValue=function(){var a=document.getElementById("aggTypeValue").value,b=document.getElementById("summaryFieldValue").value,c=document.getElementById("calcagg_formula_v_type"),d=-1;if(a===""||b=="RowCount"||b==="")c.selectedIndex=0;else{for(b=0;b<c.options.length;b++)if(c.options[b].value==a){d=b;break}if(d>=0)c.selectedIndex=d}};CSFEditor.clearWizardStep=function(){var a=document.report;if(!a)a=opener.document.report;a.nav.value=""};
CSFEditor.overrideParentgroupvalInsertLabel=function(a,b){functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("ReportAggregatesStep","matrixParentFuncInsertLabel",a,b)};
CSFEditor.overrideParentgroupvalLogic=function(a){if(document.getElementById("csfContextallLevel").checked){functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("FormulaFieldFunctions","PARENTGROUPVAL");CSFEditor.setRowBreakContext("");CSFEditor.setColBreakContext("")}else if(document.getElementById("csfContextgrandTotalLevel").checked){functionNameToPrototypeMap.PARENTGROUPVAL=LC.getLabel("FormulaFieldFunctions","PARENTGROUPVAL");CSFEditor.setRowBreakContext(LC.getLabel("ReportAggregatesStep","matrixRowGrandSummaryValue"));
CSFEditor.setColBreakContext(LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryValue"))}else{var b=document.getElementById("csfContextsub1Level")!==null&&document.getElementById("csfContextsub1Level").checked,c=document.getElementById("csfContextsub2Level")!==null&&document.getElementById("csfContextsub2Level").checked;if(a=="true")if(b){CSFEditor.overrideParentgroupvalInsertLabel(LC.getLabel("ReportAggregatesStep","matrixRowGrandSummaryValue"),LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryValue"));
CSFEditor.setRowBreakContext(document.getElementById("csfContextsub1Level").value);CSFEditor.setColBreakContext(LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryValue"))}else{if(c){CSFEditor.overrideParentgroupvalInsertLabel(document.getElementById("chosenParentLevel1").value,LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryValue"));CSFEditor.setRowBreakContext(document.getElementById("csfContextsub2Level").value);CSFEditor.setColBreakContext(LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryValue"))}}else if(b){CSFEditor.overrideParentgroupvalInsertLabel(LC.getLabel("ReportAggregatesStep",
"matrixRowGrandSummaryValue"),LC.getLabel("ReportAggregatesStep","matrixColGrandSummaryValue"));CSFEditor.setRowBreakContext(LC.getLabel("ReportAggregatesStep","matrixRowGrandSummaryValue"));CSFEditor.setColBreakContext(document.getElementById("csfContextsub1Level").value)}else if(c){CSFEditor.overrideParentgroupvalInsertLabel(LC.getLabel("ReportAggregatesStep","matrixRowGrandSummaryValue"),document.getElementById("chosenParentLevel1").value);CSFEditor.setRowBreakContext(LC.getLabel("ReportAggregatesStep",
"matrixRowGrandSummaryValue"));CSFEditor.setColBreakContext(document.getElementById("csfContextsub2Level").value)}if(document.getElementById("csfContextsub1Level")!==null&&document.getElementById("csfContextsub1Level").checked){if(document.getElementById("chosenParentLevel1")!==null)document.getElementById("chosenParentLevel1").disabled=true}else if(document.getElementById("csfContextsub2Level")!==null&&document.getElementById("csfContextsub2Level").checked){document.getElementById("chosenParentLevel1").disabled=
false;document.getElementById("chosenParentLevel1").checked=true}}};CSFEditor.insertCode=function(a,b,c){restoreSelection(document.getElementById(a));b=c&&!findDelimiters(a,"{!","}")?"{!"+b+"}":b;insertTextAtSelectionInEditor(a,b)};CSFEditor.formDisabled=false;
CSFEditor.handleTextAreaElementChange=function(a,b,c,d){handleTextAreaElementChange(a,b,c,d);c=document.getElementById("validate");d=document.getElementById("validateAndAdd");if(c&&d){if(c.className!="btnDisabled")CSFEditor.btnCheckOriginalClassName=c.className;if(d.className!="btnDisabled")CSFEditor.btnDoneOriginalClassName=c.className;a=document.getElementById(a);if(b-(!a?0:a.value.length)<0){CSFEditor.formDisabled=true;c.className="btnDisabled";d.className="btnDisabled"}else{CSFEditor.formDisabled=
false;c.className=CSFEditor.btnCheckOriginalClassName;d.className=CSFEditor.btnDoneOriginalClassName}}};var calcagg_params=["calcagg_label","calcagg_name","calcagg_formula","calcagg_type","calcagg_desc","calcagg_scale","calcagg_rowBreak","calcagg_colBreak"];function clearCalcAgg(a,b){for(var c in calcagg_params)if(calcagg_params.hasOwnProperty(c))a[calcagg_params[c]+b].value=""}function deleteCalcAgg(a){var b=document.getElementById("report");clearCalcAgg(b,a);b.nav.value="agg";b.submit()}
function copyCalcaggParams(a,b,c,d){for(var e in calcagg_params)if(calcagg_params.hasOwnProperty(e))c[calcagg_params[e]+d].value=a[calcagg_params[e]+b].value;CSFEditor.transferFuncSelectOpenParam(a,c);CSFEditor.transferFuncSelectorValueParam(a,c);CSFEditor.transferFuncCategoryValueParam(a,c);CSFEditor.transferSummaryFieldValueParam(a,c);CSFEditor.transferAggTypeValueParam(a,c)}
function submitCalcAgg(a,b){if(!CSFEditor.formDisabled){var c=document.report;if(!c)c=opener.document.report;c.target="aggcalc_popup";c.calcagg_request.value=a;c.calcagg_index.value=b;if(a=="new")clearCalcAgg(c,"_v");else if(a=="edit")copyCalcaggParams(c,b,c,"_v");else if(a=="done"||a=="validate"){var d=document.getElementById("calcagg_form");copyCalcaggParams(d,"_v",c,"_v")}c.nav.value="agg";c.submit();c.calcagg_request.value="";c.target=""}}
function finishValidCalcAgg(a){var b=opener.document.getElementById("report"),c=document.getElementById("calcagg_form");b.calcagg_index.value=a;copyCalcaggParams(c,"_v",b,a);b.calcagg_active_v.value=c.calcagg_name_v.value;b.nav.value="agg";b.submit();self.close()};
